[project]
name = "backend"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "bonnybabukachappilly", email = "bonnybabukachappilly@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "alembic==1.18.5",
    "fastapi[standard]==0.139.0",
    "httpx==0.28.1",
    "psycopg2-binary==2.9.12",
    "pydantic-settings==2.14.2",
    "pytest==9.1.1",
    "sqlalchemy==2.0.51",
    "uvicorn[standard]==0.50.0",
]

[project.scripts]
backend = "backend:main"

[build-system]
requires = ["uv_build>=0.10.3,<0.11.0"]
build-backend = "uv_build"


[tool.poe.tasks]

[tool.poe.tasks.dev]
help = "Run the FastAPI development server"
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port 8080"
cwd = "src"