"""Adding Pantry Tables

Revision ID: ad75bd5c9dc4
Revises: 47231326466f
Create Date: 2026-07-11 18:16:05.312153

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad75bd5c9dc4'
down_revision: Union[str, Sequence[str], None] = '47231326466f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pantry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('quantity_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_threshold', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('track_type', sa.Enum('QUANTITY', 'EXPIRY', 'UNTRACK', name='pantrytracktype', native_enum=False), nullable=False),
    sa.Column('low_flag', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ingredient_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pantry')
    # ### end Alembic commands ###
