"""Adding Inventory Tables

Revision ID: 780165e61b29
Revises: 
Create Date: 2026-07-07 18:35:24.297615

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '780165e61b29'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inventory',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('item_name', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('unit', sa.String(length=10), nullable=True),
    sa.Column('low_stock_threshold', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('expiry_date', sa.Date(), nullable=True),
    sa.Column('expiry_date_threshold', sa.Numeric(precision=10, scale=0), nullable=True),
    sa.Column('track_type', sa.Enum('QUANTITY', 'EXPIRY', 'UNTRACK', name='inventorytracktype', native_enum=False), nullable=False),
    sa.Column('low_flag', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inventory')
    # ### end Alembic commands ###
